services:
  postgre_database:
    image: postgres:17.0-alpine3.20
    container_name: postgre_database
    volumes:
      - postgre_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
  postgre_db: